[tool.poetry]
name = "objdetect-webrtc"
version = "0.1.0"
description = "Object detection from webcam"
authors = ["Goleg"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
aiohttp = "^3.9.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
